In [3]:
import numpy as np
data = np.array([1,2,3,4,5])
print(np.median(data))

3.0


In [5]:
mean = np.mean(data)

In [6]:
print(mean)

3.0


In [8]:
median = np.median(data)

In [9]:
print(median)

3.0


In [10]:
max = np.max(data)

In [11]:
print(max)

5


In [26]:
std_dev = np.std(data)

In [28]:
print(std_dev)

1.4142135623730951


In [29]:
total = np.sum(data)

In [30]:
print(total)

15


In [35]:
reshaped_array = data.reshape((5, 1))

In [36]:
print(reshaped_array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [38]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated = np.concatenate((array1,array2))

In [39]:
print(concatenated)

[1 2 3 4 5 6]


In [52]:
concatenated = np.linspace(0,10,5)

In [53]:
print(concatenated)

[ 0.   2.5  5.   7.5 10. ]


In [59]:
range_array = np.arange(0,10,2)

In [60]:
print(range_array)

[0 2 4 6 8]
